### ISSUE TITLE
Request to add gl transition extra lib

### ISSUE THREAD

**Issue by biaomingzhong** [homebrew-ffmpeg/homebrew-ffmpeg#66]
I want to add gl transition extra lib to my ffmpeg. https://github.com/transitive-bullshit/ffmpeg-gl-transition

is there a way  I can implement to add this feature?

**Comment by slhck** [comment]
I suppose it can be done in theory, with the help of some `if` blocks in the Formula, but it's going to be a bit convoluted, since the project you've linked to is applying a patch to the FFmpeg source code. It would be much easier if there was native support for that filter, see also https://github.com/transitive-bullshit/ffmpeg-gl-transition/issues/1. I'm inclined to say that if you need this patch, you should compile from source.

Have you seen the [`xfade` filter](http://ffmpeg.org/ffmpeg-filters.html#xfade)? Some [demos here](https://trac.ffmpeg.org/wiki/Xfade)

**Comment by biaomingzhong** [comment]
Thanks. I will try it out.

**Comment by retokromer** [comment]
I agree that submitting a patch upstream, via the `ffmpeg-devel@ffmpeg.org` mailing list, would be the best solution.

**Comment by biaomingzhong** [comment]
Thanks for the help. I think I will use `xfade` instead.
